# Basic Jekyll Configuration

# Site settings
title: Boston Eats
theme: jekyll-theme-minimal
email: your_email@example.com
description: >-  
  Hidden gem restaurants and cultures in Boston, plus community food events.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bostoneats.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
