# Basic Jekyll Configuration

# Site settings
title: Boston Eats
theme: jekyll-theme-minimal
email: your_email@example.com
description: >-  
  This is my awesome website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Bostoneats.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
